server:
  port: 9006
  
spring:
  application:
    name: COMPANY-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:88888
    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#      hostname: localhost